[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "PlantscHub"
authors = [{name = "SongLiLab", email = "songli@vt"}]
dynamic = ["version", "description"]
dependencies = [
    "sphinx"
]
