[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Agri-scHub"
authors = [{name = "Graziella", email = "graziella@lumache"}]
dynamic = ["version", "description"]
dependencies = [
    "sphinx",
    "sphinx-design",
    "sphinx-rtd-theme",
]
